# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: tarampampam/node:12-alpine
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: yarn build
      - store_artifacts:
          path: /.next
    steps:
       - add_ssh_keys:
          fingerprints:
            - "51:7a:ef:15:ad:31:3c:1f:c5:1b:50:13:a1:99:31:d5"
       - run: yarn export
       - run: yarn deploy