# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: tarampampam/node:12-alpine
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: yarn export
      - store_artifacts:
          path: out/
      - persist_to_workspace:
          root: ~/repo
          paths: out
  deploy:
    docker:
      - image: tarampampam/node:12-alpine
    working_directory: ~/repo
    steps:
       - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo
       - add_ssh_keys:
          fingerprints:
            - "51:7a:ef:15:ad:31:3c:1f:c5:1b:50:13:a1:99:31:d5"
       - run: touch out/.nojekyll
       - run: git add out/ && git commit -m \"Deploy Next.js to gh-pages [skip ci]\"
       - run: git subtree push --prefix out origin gh-pages
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build